# Example GitHub Actions workflow which provides a CI build for your Mbed CE project.

name: Test that this Mbed project compiles

# Change this to "on: push" to run the workflow on every commit instead of when a PR is submitted.
on: pull_request

jobs:
  compile:
    runs-on: ubuntu-latest
    container: ghcr.io/armmbed/mbed-os-env:master-latest
    
    strategy:
      matrix:
        mbed_target: 
          - L452RE_SIMPLE
          - L452RE_CUSTOM_PINMAP
          - L452RE_CUSTOM_CLOCK
          - L452RC_CUSTOM_MEMORY_MAP
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install python3-venv
        run: |
          apt-get update
          apt-get install -y python3-venv

      - name: Build project for ${{ matrix.mbed_target }}
        run: |
            mkdir build && cd build
            cmake .. -GNinja -DUPLOAD_METHOD=NONE -DMBED_TARGET=${{ matrix.mbed_target }} 
            ninja
